version: '3.7'

networks:
  cluster:

services:
  # EXECTION NODE -> Nethermind
  nethermind:
    image: nethermind/nethermind:${NETHERMIND_VERSION:-latest}
    restart: unless-stopped
    init: true
    networks: [ cluster ]
    environment:
      - DOTNET_BUNDLE_EXTRACT_BASE_DIR=/tmp/ethereum/nethermind
    command: >-
      --config=${NETWORK} 
      --datadir=/tmp/ethereum/nethermind 
      --JsonRpc.JwtSecretFile=/tmp/ethereum/jwtsecret/jwt.hex 
      --Sync.SnapSync=true 
      --JsonRpc.Enabled=true 
      --JsonRpc.Host=0.0.0.0 
      --JsonRpc.Port=8545 
      --JsonRpc.EngineHost=0.0.0.0
      --JsonRpc.EnginePort=8551
      --HealthChecks.Enabled=true 
      --Metrics.Enabled=true 
      --Metrics.PushGatewayUrl=http://0.0.0.0:8645/metrics
    volumes:
      - ${DATA_FOLDER:-./databases}/.nethermind:/tmp/ethereum/nethermind
      - ${DATA_FOLDER:-./databases}/jwtsecret:/tmp/ethereum/jwtsecret
    ports:
      - "127.0.0.1:${NETHERMIND_API_PORT:-8545}:8545"    # JSON-RPC port
      - "127.0.0.1:${NETHERMIND_METRICS_PORT:-8645}:8645"    # Prometheus metrics port
      - "${NETHERMIND_P2P_PORT:-30003}:30003" # P2P port (the only one exposed to the network)

  # CONSENSUS NODE -> Nimbus 
  nimbus-trusted-sync:
    image: statusim/nimbus-eth2:amd64-${NIMBUS_VERSION:-latest}
    networks: [ cluster ]
    command: >-
      --network=${NETWORK}
      trustedNodeSync
      --trusted-node-url="${CHECKPOINT_SYNC_URL:-}"
      --data-dir=/tmp/ethereum/data
    volumes:
      - ${DATA_FOLDER:-./databases}/.nimbus:/tmp/ethereum/data
  
  nimbus:
    image: statusim/nimbus-eth2:amd64-${NIMBUS_VERSION:-latest}
    restart: unless-stopped
    init: true
    user: ${UID}:${GID}
    networks: [ cluster ]
    ports:
      - "127.0.0.1:${NIMBUS_METRICS_PORT:-8008}:8008" # Prometheus metrics
      - "127.0.0.1:${NIMBUS_API_PORT:-5052}:5052" # Rest Port
      - "${NIMBUS_P2P_PORT:-9000}:9000" # P2P port (the only one exposed to the network)
    command: >-
      --network=${NETWORK}
      --data-dir=/tmp/ethereum/data
      --web3-url=http://nethermind:8551
      --jwt-secret=/tmp/ethereum/jwtsecret/jwt.hex
      --payload-builder=true
      --payload-builder-url=http://mev-boost:18550
      --rest
      --rest-address=0.0.0.0
      --rest-port=5052
      --metrics
      --metrics-address=0.0.0.0
      --metrics-port=8008 
    volumes:
      - ${DATA_FOLDER:-./databases}/.nimbus:/tmp/ethereum/data
      - ${DATA_FOLDER:-./databases}/jwtsecret:/tmp/ethereum/jwtsecret
  
  mev-boost:
    image: flashbots/mev-boost:${MEV_BOOST_VERSION:-latest}
    restart: unless-stopped
    user: ${UID}:${GID}
    init: true
    networks: [ cluster ]
    command: >-
      -${NETWORK:-}
      -min-bid 0.05
      -relay-check
      -relay ${RELAY1:-}
      -relay ${RELAY2:-}
      -relay ${RELAY3:-}

  # Metrics
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    init: true
    user: ${UID}:${GID}
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./apps-data/.prometheus:/prometheus/data
    command:
      - '--config.file=/etc/prometheus/docker-prometheus.yml'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=0.0.0.0:9090'
      - '--storage.tsdb.retention.time=1y'
      - '--web.enable-remote-write-receiver'
    networks: [ cluster ]
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_ADDRESS:-127.0.0.1:9090}:9090"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_VERSION:-latest}
    networks: [ cluster ]
    init: true
    ports:
      - "127.0.0.1:${CADVISOR_PORT:-8080}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    user: ${UID}:${GID}
    networks: [ cluster ]
    init: true
    volumes:
      - ./databases/.grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "${GRAFANA_ADDRESS:-127.0.0.1:3030}:3030"





